---
sudo: required

language: bash

services:
  - docker

jobs:
  include:
    - stage: shellcheck
      script:
        - docker pull koalaman/shellcheck
        - find . -name '*.sh' |
          xargs docker run -v $(pwd):/mnt koalaman/shellcheck
    - stage: yamllint
      language: python
      script:
        - pip install yamllint
        - yamllint $(git ls-files '*.yaml' '*.yml')
    - stage: dotbot
      os: osx
      script:
        - sed -i '' '/^mas/d' Brewfile  # remove mas-cli lines
        - ./install
