---
sudo: required

language: bash

services:
  - docker

jobs:
  include:
    - stage: shellcheck
      script:
        - docker pull koalaman/shellcheck
        - find . -name '*.sh' |
          xargs docker run -v $(pwd):/mnt koalaman/shellcheck
    - stage: yamllint
      language: python
      script:
        - pip install yamllint
        - yamllint $(git ls-files '*.yaml' '*.yml')
    - stage: dotbot
      os: osx
      script:
        # remove app store installation via mas-cli
        - sed -i '' '/^mas/d' Brewfile
        # remove .zshrc link
        - sed -i '' '/~\/.zshrc:/d' install.conf.yaml
        # do not change shell on travis
        - sed -i '' '/.\/zsh.sh/d' install.conf.yaml
        - sed -i '' '/Enable zsh if necessary/d' install.conf.yaml
        - export PATH="/nix/var/nix/profiles/default/bin:$PATH"
        - brew update
        # cf. https://github.com/Homebrew/homebrew-core/issues/26358
        - brew upgrade python
        - ./install
