---
sudo: required

language: bash

services:
  - docker

jobs:
  include:
    - stage: shellcheck
      script:
        - docker pull koalaman/shellcheck
        - find . -name '*.sh' |
          xargs docker run -v $(pwd):/mnt koalaman/shellcheck
    - stage: yamllint
      language: python
      script:
        - pip install yamllint
        - yamllint $(git ls-files '*.yaml' '*.yml')
    - stage: dotbot
      os: osx
      script:
        # remove app store installation via mas-cli
        - sed -i '' '/^mas/d' Brewfile
        # remove .zshrc link
        - sed -i '' '/~\/.zshrc:/d' install.conf.yaml
        # remove nix installation
        - head -n 33 install.conf.yaml > install.conf.yaml.tmp
        - mv install.conf.yaml.tmp install.conf.yaml
        - ./install
