---
sudo: required

language: bash

services:
  - docker

jobs:
  include:
    - stage: shellcheck
      script:
        - docker pull koalaman/shellcheck
        - find . -name '*.sh' -not -path './tmux/*' |
          xargs docker run -v $(pwd):/mnt koalaman/shellcheck
    - stage: yamllint
      language: python
      script:
        - pip install yamllint
        - yamllint $(git ls-files '*.yaml' '*.yml')
    - stage: dotbot
      os: osx
      script:
        # do not change shell on travis
        - sed -i '' '30,32d' default.conf.yaml
        # remove .zshrc link
        - sed -i '' '/~\/.zshrc:/d' default.conf.yaml
        # remove app store installation via mas-cli
        - sed -i '' '/^mas/d' Brewfile
        - sed -i '' '/^mas/d' home/Brewfile
        # do not try installing virtualbox on travis
        - sed -i '' '/^cask "virtualbox"$/d' Brewfile
        - ./install home
