---
sudo: required

language: bash

services:
  - docker

jobs:
  include:
    - stage: shellcheck
      script:
        - docker pull koalaman/shellcheck
        - find . -name '*.sh' |
          xargs docker run -v $(pwd):/mnt koalaman/shellcheck
    - stage: yamllint
      language: python
      script:
        - pip install yamllint
        - yamllint $(git ls-files '*.yaml' '*.yml')
    - stage: dotbot
      os: osx
      script:
        # do not change shell on travis
        - sed -i '' '35,37d' install.conf.yaml
        # remove .zshrc link
        - sed -i '' '/~\/.zshrc:/d' install.conf.yaml
        # put nix into path
        - export PATH="/nix/var/nix/profiles/default/bin:$PATH"
        # disable homebrew
        - sed -i '' '/- brewfile:/d' install.conf.yaml
        - sed -i '' '/- Brewfile/d' install.conf.yaml
        - ./install
    - os: osx
      script:
        # do not change shell on travis
        - sed -i '' '35,37d' install.conf.yaml
        # remove .zshrc link
        - sed -i '' '/~\/.zshrc:/d' install.conf.yaml
        # remove app store installation via mas-cli
        - sed -i '' '/^mas/d' Brewfile
        # cf. https://github.com/Homebrew/homebrew-core/issues/26358
        - brew upgrade python
        # cf. https://github.com/Homebrew/homebrew-core/issues/24978
        - brew uninstall --force mercurial; brew install mercurial
        # disable nix
        - sed -i '' '/- nix:/d' install.conf.yaml
        - sed -i '' '/- all/d' install.conf.yaml
        - ./install
