---
sudo: required

language: bash

services:
  - docker

jobs:
  include:
    - stage: shellcheck
      script:
        - docker pull koalaman/shellcheck
        - find . -name '*.sh' -not -path './tmux/*' |
          xargs docker run -v $(pwd):/mnt koalaman/shellcheck
    - stage: yamllint
      language: python
      script:
        - pip install yamllint
        - yamllint $(git ls-files '*.yaml' '*.yml')
    - stage: dotbot
      os: osx
      osx_image: xcode11
      script:
        # do not set shell on travis
        - echo '' > zsh.sh
        # remove app store installation via mas-cli
        - sed -i '' '/^mas/d' Brewfile
        - sed -i '' '/^mas/d' home/Brewfile
        # do not try installing virtualbox on travis
        - sed -i '' '/^cask "virtualbox"$/d' Brewfile
        - rm ~/.gitconfig
        - brew unlink python@2
        - ./install home
