tap "buo/cask-upgrade"
tap "homebrew/core"
tap "homebrew/bundle"
tap "pivotal/tap"
tap "caskroom/cask"
brew "adr-tools"
brew "jrnl"
brew "m-cli"
brew "mas"
brew "pinentry-mac"
brew "pivotal/tap/springboot"
cask "1password"
cask "aerial"
cask "atom"
cask "chromium"
cask "cliqz"
cask "firefox"
cask "flash-npapi"
cask "flux"
cask "franz"
cask "freemind"
cask "grandperspective"
cask "hipchat"
cask "inkscape"
cask "intellij-idea"
cask "iterm2"
cask "keepassx"
cask "libreoffice"
cask "mat"
cask "minikube"
cask "mist"
cask "postbox"
cask "postman"
cask "pycharm-ce"
cask "skype-for-business"
cask "spotify"
cask "tunnelblick"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "xquartz"
cask "zoomus"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Things3", id: 904280696
mas "Xcode", id: 497799835
