tap "buo/cask-upgrade"
tap "homebrew/dupes"
tap "homebrew/science"
tap "homebrew/core"
tap "homebrew/versions"
tap "homebrew/bundle"
tap "pivotal/tap"
tap "caskroom/cask"
cask "java"
brew "antigen"
brew "coreutils"
brew "doitlive"
brew "findutils"
brew "geth"
brew "hugo"
brew "jenkins"
brew "kafka"
brew "kubernetes-helm"
brew "libyaml"
brew "m-cli"
brew "mas"
brew "node"
brew "openconnect", args: ["HEAD"]
brew "readline"
brew "openshift-cli"
brew "pinentry-mac"
brew "prometheus"
brew "sqlite"
brew "python"
brew "spotbugs"
brew "terraform_landscape"
brew "pivotal/tap/springboot"
cask "1password"
cask "aerial"
cask "atom"
cask "basictex"
cask "chromium"
cask "cliqz"
cask "firefox"
cask "flash-npapi"
cask "flux"
cask "franz"
cask "freemind"
cask "gogland"
cask "hipchat"
cask "inkscape"
cask "intellij-idea"
cask "iterm2"
cask "jce-unlimited-strength-policy"
cask "keepassx"
cask "libreoffice"
cask "mat"
cask "minikube"
cask "mist"
cask "nix"
cask "postbox"
cask "postman"
cask "pycharm-ce"
cask "rstudio"
cask "skype-for-business"
cask "spotify"
cask "tunnelblick"
cask "vagrant"
cask "virtualbox"
cask "vlc"
cask "xquartz"
cask "zoomus"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Things3", id: 904280696
