cask "drawio"
cask "freeplane"
cask "gpg-suite"
cask "joplin"
cask "keepassx"
cask "microsoft-teams"
cask "slack"
cask "tunnelblick"
cask "zoom"
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Xcode", id: 497799835
