name: dotfiles

on: [push]

jobs:
  base:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Prepare for CI
      run: |
        echo '' > zsh.sh
        sed -i '' '/^mas/d' Brewfile
        rm '/usr/local/bin/aws' '/usr/local/bin/aws_completer' '/usr/local/bin/go' '/usr/local/bin/gofmt'
    - name: Execute base install
      run:  ./install
    - name: Execute work install
      run: ./install work
