name: dotfiles

on: [push]

jobs:
  base:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Prepare for CI
      run: |
        echo '' > zsh.sh
        sed -i '' '/^mas/d' Brewfile
    - name: Execute base install
      run:  ./install
