name: Work Install

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Execute work install
      run:  ./install work
